<?php

namespace App\Services;

use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

class IprogSmsService
{
    protected $apiToken;
    protected $apiUrl;
    protected $smsApiUrl;

    public function __construct()
    {
        $this->apiToken  = config('iprog.api_token');
        $this->apiUrl    = config('iprog.api_url');
        $this->smsApiUrl = config('iprog.sms_api_url');
    }

    /**
     * Send OTP via IPROG's dedicated OTP endpoint.
     * The API generates the OTP and returns it in the response.
     *
     * @param string $phoneNumber Local format (e.g., 09123456789)
     * @param string|null $message Custom message with :otp placeholder (optional)
     * @param int $expiresInMinutes Expiration in minutes (default 5)
     * @return string The OTP generated by the API
     * @throws \Exception
     */
    public function sendOtp(string $phoneNumber, ?string $message = null, int $expiresInMinutes = 5): string
    {
        if (empty($this->apiToken)) {
            throw new \Exception('IPROG API token not configured.');
        }

        $payload = [
            'api_token' => $this->apiToken,
            'phone_number' => $phoneNumber,
            'expires_in_minutes' => $expiresInMinutes,
        ];

        if ($message !== null) {
            $payload['message'] = $message; // use :otp placeholder for the code
        }

        Log::info('IPROG OTP request payload', $payload);

        $response = Http::withHeaders([
            'Accept' => 'application/json',
            'Content-Type' => 'application/json',
        ])
        ->timeout(30)
        ->withOptions(['verify' => false])
        ->post($this->apiUrl, $payload);

        Log::info('IPROG OTP response', [
            'status' => $response->status(),
            'body'   => $response->body(),
        ]);

        // If the response is not successful, check if it still contains success indicators
        if (!$response->successful()) {
            $body = $response->body();
            // Some APIs return a success message even with a non-200 status
            if (str_contains($body, 'successfully') || str_contains($body, 'queued') || str_contains($body, 'sent')) {
                // It's actually a success, but we need to extract OTP if possible
                $data = $response->json();
                if (isset($data['data']['otp_code'])) {
                    return $data['data']['otp_code'];
                }
                // If we can't extract OTP, we still consider it a success (but throw an exception to avoid missing OTP)
                throw new \Exception('OTP sent but OTP code not returned. Please check API configuration.');
            }

            $errorBody = $response->json();
            $errorMsg = $errorBody['error'] ?? $errorBody['message'] ?? $response->body();
            throw new \Exception('OTP sending failed: ' . $errorMsg);
        }

        $data = $response->json();

        // Extract the OTP from the nested 'data' object
        if (isset($data['data']['otp_code'])) {
            return $data['data']['otp_code'];
        }

        // If the API doesn't return OTP, check if status indicates success
        if (isset($data['status']) && ($data['status'] === 'success' || $data['status'] === 'OK')) {
            throw new \Exception('OTP sent but not returned in response. Please check API configuration.');
        }

        // Otherwise, treat as error
        $error = $data['message'] ?? $data['error'] ?? 'Unknown IPROG error';
        Log::error('IPROG OTP error', ['response' => $data]);
        throw new \Exception('IPROG error: ' . $error);
    }

    /**
     * Send a non‑OTP SMS message.
     *
     * @param string $phoneNumber Recipient phone number (can be local or international, e.g., 09123456789 or +639123456789)
     * @param string $message The message content
     * @return bool
     * @throws \Exception
     */
    public function sendSms(string $phoneNumber, string $message): bool
    {
        if (empty($this->apiToken)) {
            throw new \Exception('IPROG API token not configured.');
        }

        // Trim the message to avoid accidental newline issues
        $message = trim($message);

        // Ensure the phone number starts with '+'
        if (substr($phoneNumber, 0, 1) !== '+') {
            $phoneNumber = '+' . $phoneNumber;
        }

        $payload = [
            'api_token'    => $this->apiToken,
            'phone_number' => $phoneNumber,
            'message'      => $message,
        ];

        Log::info('IPROG SMS request payload', $payload);

        $response = Http::withHeaders([
            'Accept' => 'application/json',
            'Content-Type' => 'application/json',
        ])
        ->timeout(30)
        ->withOptions(['verify' => false])
        ->post($this->smsApiUrl, $payload);

        Log::info('IPROG SMS response', [
            'status' => $response->status(),
            'body'   => $response->body(),
        ]);

        // If the HTTP call failed (4xx/5xx), check if the body indicates success anyway
        if (!$response->successful()) {
            $body = $response->body();
            // Look for success indicators in the response body
            if (str_contains($body, 'successfully') || str_contains($body, 'queued') || str_contains($body, 'sent')) {
                // It's a success – return true without throwing
                Log::info('IPROG SMS accepted despite non-2xx status', ['body' => $body]);
                return true;
            }

            $errorBody = $response->json();
            $errorMsg = $errorBody['error'] ?? $errorBody['message'] ?? $response->body();
            throw new \Exception('SMS sending failed: ' . $errorMsg);
        }

        // Decode the JSON response
        $data = $response->json();

        // Some APIs return an explicit error field even on 200
        if (isset($data['error'])) {
            throw new \Exception('IPROG error: ' . $data['error']);
        }

        // If there's a status field, check it (case-insensitive)
        if (isset($data['status'])) {
            if (in_array(strtolower($data['status']), ['success', 'ok', 'sent'])) {
                return true;
            }
            // If status is something else, treat as error
            throw new \Exception('IPROG error: ' . ($data['message'] ?? 'Unknown status'));
        }

        // If we have a message_id or success flag, assume it worked
        if (isset($data['message_id']) || isset($data['success'])) {
            return true;
        }

        // Fallback: if we got a 2xx response and no error indicators, we assume success
        return true;
    }
}
